name: Puppies Continuous Integration

# NOTE: The strategy.matrix section of each job MUST have the same matrix variations

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build:
    name: Build and Unit Test

    strategy: 
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout 
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx
      
    - name: Dotnet Test Reporter
      if: always()
      uses: bibipkins/dotnet-test-reporter@v1.5.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test Results'
        results-path: ./PuppiesTest/TestResults/*.trx
        coverage-path: ./PuppiesTest/TestResults/coverage.xml
        coverage-threshold: 0
        
    - name: Publish build
      run: dotnet publish Puppies -o build
      
    - name: Tar Build
      run: tar -cvf build-${{ matrix.os }}-${{ matrix.dotnet-version }}.tar.gz build
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
          name: build-${{ matrix.os }}-${{ matrix.dotnet-version }}
          path: build-${{ matrix.os }}-${{ matrix.dotnet-version }}.tar.gz
      
      
        
  acceptance_test:
    name: Acceptance Test
    needs: build

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.dotnet-version }}
          
      - name: Expand Build Tar
        run:  tar -xvf build-${{ matrix.os }}-${{ matrix.dotnet-version }}.tar.gz
        
      - name: Start Application
        run: echo "TODO - start app"
        
      - name: Run Acceptance Tests
        run: echo "TODO - run acceptance tests"
        
      - name: Stop Application
        run: echo "TODO - stop app"
          
  package:
    name: Package
    needs: acceptance_test
    if: github.ref == 'refs/heads/main'

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        dotnet-version: [ 8.0.x ]

    runs-on: ${{ matrix.os }}
        
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: build-${{ matrix.os }}-${{ matrix.dotnet-version }}
          
      - name: Get Timestamp
        id: date
        run: echo "::set-output name=timestamp::$(date +'%Y-%m-%d-%H-%M-%S')"
        
      - name: Publish Draft Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build-${{ matrix.os }}-${{ matrix.dotnet-version }}.tar.gz
          tag: ${{ steps.date.outputs.timestamp }}-${{ github.sha }}
          draft: true
          
