name: Puppies Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Unit Test

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx
    - name: Dotnet Test Reporter
      if: always()
      uses: bibipkins/dotnet-test-reporter@v1.5.3
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        comment-title: 'Unit Test Results'
        results-path: ./PuppiesTest/TestResults/*.trx
        coverage-path: ./PuppiesTest/TestResults/coverage.xml
        coverage-threshold: 0
        
  acceptance_test:
    runs-on: ubuntu-latest
    name: Package

    needs: build

    steps:
      - name: TODO
        run: echo "TODO"  
  
  package:
    runs-on: ubuntu-latest
    name: Package
    
    needs: acceptance_test
    
    steps:
      - name: TODO
        run: echo "TODO"
